package com.example.ui.screens

import android.widget.Toast
import androidx.compose.ui.platform.LocalContext
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.example.ui.SchemaViewModel
import com.example.data.ColumnEntity

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TableDetailScreen(
    tableId: Long,
    viewModel: SchemaViewModel,
    onBack: () -> Unit
) {
    val allTables by viewModel.allTables.collectAsStateWithLifecycle()
    val tableWithCols = allTables.find { it.table.tableId == tableId }

    val context = LocalContext.current
    var isGenerating by remember { mutableStateOf(false) }

    if (tableWithCols == null) {
        onBack()
        return
    }

    var showEditNameDialog by remember { mutableStateOf(false) }
    var editName by remember { mutableStateOf("") }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(tableWithCols.table.name) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                actions = {
                    IconButton(onClick = {
                        if (isGenerating) return@IconButton
                        isGenerating = true
                        viewModel.autoGenerateColumns(
                            tableId = tableId,
                            tableName = tableWithCols.table.name,
                            onSuccess = {
                                isGenerating = false
                                Toast.makeText(context, "Columns generated by AI", Toast.LENGTH_SHORT).show()
                            },
                            onError = { error ->
                                isGenerating = false
                                Toast.makeText(context, error, Toast.LENGTH_LONG).show()
                            }
                        )
                    }) {
                         if (isGenerating) {
                             CircularProgressIndicator(modifier = Modifier.size(24.dp), color = MaterialTheme.colorScheme.onSurface)
                         } else {
                             Icon(Icons.Default.Refresh, contentDescription = "Auto Generate schema")
                         }
                    }
                    IconButton(onClick = {
                        editName = tableWithCols.table.name
                        showEditNameDialog = true
                    }) {
                        Icon(Icons.Default.Edit, contentDescription = "Edit Name")
                    }
                }
            )
        },
        floatingActionButton = {
            FloatingActionButton(
                onClick = { viewModel.addColumn(tableId) },
                containerColor = MaterialTheme.colorScheme.secondaryContainer,
                contentColor = MaterialTheme.colorScheme.onSecondaryContainer
            ) {
                Icon(Icons.Default.Add, contentDescription = "Add Column")
            }
        }
    ) { paddingValues ->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .imePadding(),
            contentPadding = PaddingValues(bottom = 80.dp)
        ) {
            items(tableWithCols.columns, key = { it.columnId }) { column ->
                ColumnEditorCard(
                    column = column,
                    onUpdate = { viewModel.updateColumn(it) },
                    onDelete = { viewModel.deleteColumn(column) }
                )
            }
        }
    }

    if (showEditNameDialog) {
        AlertDialog(
            onDismissRequest = { showEditNameDialog = false },
            title = { Text("Edit Table Name") },
            text = {
                OutlinedTextField(
                    value = editName,
                    onValueChange = { editName = it },
                    singleLine = true
                )
            },
            confirmButton = {
                Button(onClick = {
                    if (editName.isNotBlank()) {
                        viewModel.updateTable(tableWithCols.table.copy(name = editName))
                    }
                    showEditNameDialog = false
                }) {
                    Text("Save")
                }
            },
            dismissButton = {
                TextButton(onClick = { showEditNameDialog = false }) {
                    Text("Cancel")
                }
            }
        )
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ColumnEditorCard(
    column: ColumnEntity,
    onUpdate: (ColumnEntity) -> Unit,
    onDelete: () -> Unit
) {
    var expandedType by remember { mutableStateOf(false) }
    val types = listOf("INTEGER", "TEXT", "BLOB", "REAL", "NUMERIC")

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 8.dp),
        elevation = CardDefaults.cardElevation(defaultElevation = 0.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
        shape = androidx.compose.foundation.shape.RoundedCornerShape(16.dp),
        border = androidx.compose.foundation.BorderStroke(1.dp, MaterialTheme.colorScheme.outline)
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                OutlinedTextField(
                    value = column.name,
                    onValueChange = { onUpdate(column.copy(name = it)) },
                    label = { Text("Column Name") },
                    modifier = Modifier.weight(1f)
                )
                IconButton(onClick = onDelete) {
                    Icon(Icons.Default.Delete, contentDescription = "Delete", tint = MaterialTheme.colorScheme.error)
                }
            }
            
            Spacer(modifier = Modifier.height(8.dp))
            
            Row(verticalAlignment = Alignment.CenterVertically) {
                ExposedDropdownMenuBox(
                    expanded = expandedType,
                    onExpandedChange = { expandedType = !expandedType },
                    modifier = Modifier.weight(1f)
                ) {
                    OutlinedTextField(
                        value = column.type,
                        onValueChange = {},
                        readOnly = true,
                        label = { Text("Data Type") },
                        trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = expandedType) },
                        modifier = Modifier.menuAnchor()
                    )
                    ExposedDropdownMenu(
                        expanded = expandedType,
                        onDismissRequest = { expandedType = false }
                    ) {
                        types.forEach { typeOption ->
                            DropdownMenuItem(
                                text = { Text(typeOption) },
                                onClick = {
                                    onUpdate(column.copy(type = typeOption))
                                    expandedType = false
                                }
                            )
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(8.dp))

            OutlinedTextField(
                value = column.defaultValue,
                onValueChange = { onUpdate(column.copy(defaultValue = it)) },
                label = { Text("Default Value") },
                modifier = Modifier.fillMaxWidth()
            )

            Spacer(modifier = Modifier.height(8.dp))

            OutlinedTextField(
                value = column.foreignKeyReferences,
                onValueChange = { onUpdate(column.copy(foreignKeyReferences = it)) },
                label = { Text("Foreign Key References (e.g. users(id))") },
                modifier = Modifier.fillMaxWidth()
            )

            Spacer(modifier = Modifier.height(16.dp))

            // Checkboxes
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                LabeledCheckbox("PK", column.isPrimaryKey) { onUpdate(column.copy(isPrimaryKey = it)) }
                LabeledCheckbox("AutoInc", column.isAutoIncrement) { onUpdate(column.copy(isAutoIncrement = it)) }
                LabeledCheckbox("NotNull", column.isNotNull) { onUpdate(column.copy(isNotNull = it)) }
                LabeledCheckbox("Unique", column.isUnique) { onUpdate(column.copy(isUnique = it)) }
            }
        }
    }
}

@Composable
fun LabeledCheckbox(label: String, checked: Boolean, onCheckedChange: (Boolean) -> Unit) {
    Row(verticalAlignment = Alignment.CenterVertically) {
        Checkbox(checked = checked, onCheckedChange = onCheckedChange)
        Text(text = label, style = MaterialTheme.typography.bodySmall)
        Spacer(modifier = Modifier.width(4.dp))
    }
}
